# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0a70bc53836dede57096f5b86df10ff7c50e032755da0808d7682f1eb6b1c26d3c9b8926038d86b76ecc6967fd738686541e83c233b8037dc83647a7d539ec3

test:
  secret_key_base: e976a6cb0d70193b0cd38b5542d16e972e2b54cbf9076de039ba92e61533a8e43b7f8fffc3441dfc1abe89f5ff3c711b3451480231f517b379b0df7f1d5ac85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
